apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-deployment
  labels:
    app: cats
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: cats # this should match the selector in service.yml
    spec:
      serviceAccountName: ${NAMESPACE}
      containers:
        - name: cats
          image: ${REGISTRY}/${REPOSITORY}:cats-${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: rds-mssql-instance-output
                  key: rds_instance_address
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-mssql-instance-output
                  key: database_username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-mssql-instance-output
                  key: database_password
            - name: AWS__Bucket
              valueFrom:
                secretKeyRef:
                  name: s3-bucket-output
                  key: bucket_name
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: config
                  key: RABBIT_USER
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: config
                  key: RABBIT_PASS
            - name: DOTNET_ENVIRONMENT
              value: "${DOTNET_ENVIRONMENT}"
            - name: ConnectionStrings__CatsDb
              value: "Server=$(DATABASE_ADDRESS);Database=CatsDb;User Id=$(DATABASE_USERNAME);Password=$(DATABASE_PASSWORD);TrustServerCertificate=True;"
            - name: ConnectionStrings__rabbit
              value: "amqp://$(RABBIT_USER):$(RABBIT_PASS)@rabbitmq-service:5672"
            - name: AWS__RootFolder
              value: "Files"